version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    environment:
      - PORT=4567
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=example_db
    ports:
      - "4567:4567"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: